#define POINTS 20
// #define SPRNTRL_POINTS 15  // free points for Supernatural
#define KNDR_DISCPILINE_COST 2
#define KNDR_NEW_DISCPILINE_COST 1
#define CTHN_DISCPILINE_COST 2
#define CTHN_NEW_DISCPILINE_COST 1
#define GHL_DISCIPLINE_COST 2
